---

stages:
  - deploy
  - composer


    #syntax:  
    #tags:
    #- deploy
    #stage: deploy
    #tags: 
    #- apiassets

deploy_environment:
  stage: deploy
  tags:
   - contable
  script:
   - echo "${CI_COMMIT_REF_NAME}"
   - tools/deploy-git.sh $CI_COMMIT_REF_NAME
  when: always
  environment:
    name: ${CI_COMMIT_REF_NAME}

composer_environment:
  stage: composer
  script:
   - echo "${CI_COMMIT_REF_NAME}"
   - tools/composer.sh $CI_COMMIT_REF_NAME
  when: always
  environment:
    name: ${CI_COMMIT_REF_NAME}
