activos:
    resource: "@activosBundle/Resources/config/routing.yml"
    prefix:   /

my:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
