# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

#    firewalls:
#        restricted_area:
#            pattern:          ^/
#            anonymous:        ~
#            imag_ldap:
#                check_path:     /login_check
#                login_path:     /login
#                csrf_provider: form.csrf_provider
#                intention: authenticate
#                provider: ldap
#                use_referer: true
#                default_target_path: /
#            logout:
#                path:           /logout
#                target:         /

#    providers:
#        ldap:
#            id: imag_ldap.security.user.provider

#    encoders:
#        IMAG\LdapBundle\User\LdapUser: plaintext

#    access_control:
#        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
#       #- { path: ^/,               roles: IS_AUTHENTICATED_ANONYMOUSLY }

#imag_ldap:
#  client:
#    host: ad.upr.edu.cu
#    port: 389
#    version: 3 # Optional
#    username: frank.vigil
#    password: tengo26anno
##    network_timeout:
#    referrals_enabled: false
##    bind_username_before:
##    skip_roles:

#  user:
#    base_dn: dc=upr,dc=edu,dc=cu
#    filter: (ObjectClass=person) #Optional
#    name_attribute: sAMAccountName
##    attributes: 

#  role:
#    base_dn: dc=upr,dc=edu,dc=cu
#    filter: (ObjectClass=group) #Optional
#    name_attribute: cn
#    user_attribute: member
#    user_id: dn
##    user_id: [ dn or username ] #Default dn

##  user_class: IMAG\LdapBundle\User\LdapUser