activos_homepage:
    path:     /
    defaults: { _controller: activosBundle:Default:home }

load_Activos:
    path:     /activos
    defaults: { _controller: activosBundle:Default:activos }

activos:
    path:     /activos_contables
    defaults: { _controller: activosBundle:Default:index }

load_Activos_cnmb:
    path:     /activos_cnmb
    defaults: { _controller: activosBundle:Default:activos_cnmb }
