activos_homepage:
    path:     /
    defaults: { _controller: activosBundle:Default:home }

load_Activos:
    path:     /activos
    defaults: { _controller: activosBundle:Default:activos }

activos:
    path:     /activos_contables
    defaults: { _controller: activosBundle:Default:index }

load_Activos_cnmb:
    path:     /activos_cnmb
    defaults: { _controller: activosBundle:Default:activos_cnmb }

load_Cnmb:
    path:     /tipocnmb
    defaults: { _controller: activosBundle:Default:tipocnmb }

inventario:
    path:     /user/inventario
    defaults: { _controller: activosBundle:Default:inventario }

load_NoInventario:
    path:     /Locate_inventario
    defaults: { _controller: activosBundle:Default:Locate_inventario }

load_Activos_upr:
    path:     /load_Activos_upr
    defaults: { _controller: activosBundle:Default:activos_upr}